version: '3.2'

services:
  thekevin:
    image: thekevjames/thekev.in:latest
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 20s
      update_config:
        parallelism: 1
        monitor: 20s
    secrets:
      - dropbox_token
      - sentry_dsn_thekevin

secrets:
  dropbox_token:
    external: true
  sentry_dsn_thekevin:
    external: true
