version: 2

jobs:
  lint:
    docker:
      - image: python:3.7.1
    steps:
      - checkout
      - run: pip install pre-commit
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit install-hooks
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: pre-commit run --all-files

  hexclock:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: mkdir -p artifacts/hexclock
      - run: cp shared/* artifacts/hexclock/
      - run: cp hexclock/* artifacts/hexclock/
      - run: minify --recursive --output artifacts/ artifacts/
      - persist_to_workspace:
          root: artifacts
          paths:
            - hexclock/

  octodash:
    docker:
      - image: node:10.3.0-alpine
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: cd octodash && npm install --production
      - run: cd octodash && npm run build
      - run: mkdir -p artifacts
      - run: mv octodash/build artifacts/octodash
      - persist_to_workspace:
          root: artifacts
          paths:
            - octodash/

  octodash-extension:
    docker:
      - image: node:10.3.0
    environment:
      OCTODASH_APP_ID: gpdoaoigpdmgpfebclknegmdkaamcdpf
    steps:
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install -y jq zip
            npm install -g chrome-web-store-item-property-cli
      - checkout
      - attach_workspace:
          at: artifacts
      - run:
          name: increment build version
          command: |
            CURR="$(chrome-web-store-item-property "${OCTODASH_APP_ID}" | jq '.version' | tr -d '"')"
            TARG="$(jq '.version' octodash/public/manifest.json | tr -d '"')"
            [[ "${CURR}" == "${TARG}"* ]] && TARG+="."$(($(echo "${CURR}" | sed 's/.*\.//')+1)) || TARG+=".0"
            jq ".version = \"${TARG}\"" octodash/public/manifest.json > artifacts/octodash/manifest.json
            cat artifacts/octodash/manifest.json
      - run: mkdir -p extensions
      - run: zip -r extensions/octodash.zip artifacts/octodash/*
      - persist_to_workspace:
          root: extensions
          paths:
            - octodash.zip

  quotes:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates curl jq openssl
      - checkout
      - run: mkdir -p artifacts/quotes
      - run: cp shared/* artifacts/quotes/
      - run: cp quotes/* artifacts/quotes/
      - run:
          name: get quotes
          command: |
            curl -X POST https://content.dropboxapi.com/2/files/download \
                -H "Authorization: Bearer ${DROPBOX_TOKEN}" \
                -H "Dropbox-API-Arg: {\"path\": \"/vimwiki/quotes.wiki\"}" \
                -o /quotes.wiki
            jq -n --arg x "$(cat /quotes.wiki)" '$x | split("\n")' > artifacts/quotes/quotes.json
      - run: minify --recursive --output artifacts/ artifacts/
      - persist_to_workspace:
          root: artifacts
          paths:
            - quotes/

  site:
    docker:
      - image: python:3.7.1
    steps:
      - checkout
      - run: python3 -m pip install -r site/requirements.txt
      - run: cp shared/* site/static/
      - run: python3 site/build.py
      - run: pygmentize -S emacs -f html -a .highlight > site/build/emacs.css
      - persist_to_workspace:
          root: site
          paths:
            - build/

  site-minify:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - attach_workspace:
          at: site
      - run: minify --recursive --html-keep-document-tags --output site/build/ site/build/
      - persist_to_workspace:
          root: site
          paths:
            - build/

  webcycle:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: mkdir -p artifacts/webcycle
      - run: cp shared/* artifacts/webcycle/
      - run: cp webcycle/* artifacts/webcycle/
      - run: minify --recursive --output artifacts/ artifacts/
      - persist_to_workspace:
          root: artifacts
          paths:
            - webcycle/

  www-redir:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: mkdir -p www/redir
      - run: cp www-redir/* www/redir/
      - run: minify --recursive --html-keep-document-tags --output www/redir/ www/redir/
      - persist_to_workspace:
          root: www
          paths:
            - redir/

  upload:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run:
          name: authenticate with google cloud
          command: |
            echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: artifacts
      - run: gsutil -m cp -r artifacts/* gs://thekevjames-artifacts
      - attach_workspace:
          at: site
      - run: gsutil -m cp -r site/build/* gs://thekev.in
      - attach_workspace:
          at: www
      - run: gsutil -m cp -r www/redir/* gs://www.thekev.in

  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      OCTODASH_APP_ID: gpdoaoigpdmgpfebclknegmdkaamcdpf
    steps:
      - attach_workspace:
          at: extensions
      - run: APP_ID=${OCTODASH_APP_ID} publish extensions/octodash.zip

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint
      - hexclock:
          requires:
            - lint
      - octodash:
          requires:
            - lint
      - octodash-extension:
          requires:
            - octodash
      - quotes:
          requires:
            - lint
      - site:
          requires:
            - lint
      - site-minify:
          requires:
            - site
      - webcycle:
          requires:
            - lint
      - www-redir:
          requires:
            - lint
      - upload:
          requires:
            - hexclock
            - octodash
            - quotes
            - site-minify
            - webcycle
            - www-redir
          filters:
            branches:
              only: master
      - publish:
          requires:
            - octodash-extension
          filters:
            branches:
              only: master
