version: 2

jobs:
  lint:
    docker:
      - image: python:3.6.4
    steps:
      - checkout
      - run: pip install pre-commit
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit run --all-files
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit

  thekevin:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t web .
      - deploy:
          name: login to dockerhub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: push image (hash)
          command: |
            docker tag web "thekevjames/thekev.in:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
            docker push "thekevjames/thekev.in:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
      - deploy:
          name: push image (branch)
          command: |
            docker tag web "thekevjames/thekev.in:${CIRCLE_BRANCH}"
            docker push "thekevjames/thekev.in:${CIRCLE_BRANCH}"
      - deploy:
          name: push image (latest)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag web thekevjames/thekev.in:latest
              docker push thekevjames/thekev.in:latest
            fi

  hexclock:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: mkdir -p build/hexclock
      - run: cp shared/* build/hexclock/
      - run: cp hexclock/* build/hexclock/
      - run: minify --recursive --match=".*.css" --type=css --output build/ build/
      - run: minify --recursive --match=".*.js" --type=js --output build/ build/
      - persist_to_workspace:
          root: build
          paths:
            - hexclock/

  quotes:
    docker:
      - image: mysocialobservations/docker-tdewolff-minify
    steps:
      - run:
          name: install dependencies
          command: apk add --update ca-certificates openssl
      - checkout
      - run: mkdir -p build/quotes
      - run: cp shared/* build/quotes/
      - run: cp quotes/* build/quotes/
      - run: minify --recursive --match=".*.css" --type=css --output build/ build/
      - run: minify --recursive --match=".*.js" --type=js --output build/ build/
      - persist_to_workspace:
          root: build
          paths:
            - quotes/

  upload:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run:
          name: authenticate with google cloud
          command: |
            echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gsutil -m cp -r build/* gs://thekevjames-artifacts

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - deploy:
          name: deploy image
          command: |
            ssh -oStrictHostKeyChecking=no kevin@thekev.in "
              sudo docker service update --image thekevjames/thekev.in:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8} thekevjames_thekevin
            "

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint
      - thekevin:
          context: org-global
          requires:
            - lint
      - hexclock
      - quotes
      - upload:
          requires:
            - hexclock
            - quotes
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - thekevin
            - upload
          filters:
            branches:
              only: master
